Repository icecube/pisa, pull requests merged in 2024-07, with the labels that each got.

#780 Stage and pipeline related documentation touch ups
  pisa/core/pipeline.py
  pisa/core/stage.py
  pisa/stages/README.md
  pisa_examples/pisa_modes.ipynb
Labels: documentation

#781 Update README.md
  pisa/analysis/README.md
Labels: enhancement, documentation

#756 adding stage for external osc calc
  pisa/stages/osc/external.py
  pisa/stages/osc/layers.py
Labels: enhancement

#783 fix plotting 2d arrays (not caught by unit tests)
  pisa/utils/plotter.py
Labels: bug
